### ISSUE TITLE
Improve style for language/difficulty styles

### ISSUE THREAD

**Issue by ecumene** [FarhanaSunny/Tongue-Twisters-Generator#27]
<img width="276" alt="Screenshot 2024-01-14 at 3 50 12 PM" src="https://github.com/FarhanaSunny/Tongue-Twisters-Generator/assets/6249465/6c350369-42e9-461f-8e35-c621271fc04f">

```css
.languageStyle {
    border-radius: 1rem;
    color: white;
    background-color: #ef4444;
    padding: 0.25rem 0.5rem;
    display: inline;
}
```
